#############################################################################
# Makefile for building: SymbianZoneApp
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? 10. ??? 21:01:52 2015
# Project:  SymbianZoneApp.pro
# Template: app
# Command: c:\qtsdk\symbian\sdks\symbiansr1qt474\bin\qmake.exe -spec ..\..\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o bld.inf SymbianZoneApp.pro
#############################################################################

MAKEFILE          = Makefile
QMAKE             = c:\qtsdk\symbian\sdks\symbiansr1qt474\bin\qmake.exe
DEL_FILE          = del /q 2> NUL
DEL_DIR           = rmdir
CHK_DIR_EXISTS    = if not exist
MKDIR             = mkdir
MOVE              = move
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make
SBS               = sbs

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_USE_MATH_H_FLOATS -DQ_COMPONENTS_SYMBIAN -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH	 =  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtCore"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtGui"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtXml"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtDeclarative"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/mkspecs/common/symbian"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis/sys"  -I"C:/workspace/SymbianZoneApp/qmlapplicationviewer"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis/stlportv5"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/mw"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/loc"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw/loc"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/loc/sc"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw/loc/sc"  -I"C:/workspace/SymbianZoneApp/moc"  -I"C:/workspace/SymbianZoneApp"  -I"C:/workspace/SymbianZoneApp/rcc"  -I"C:/workspace/SymbianZoneApp/ui" 
first: default

all: debug release

default: debug-winscw
qmake:
	$(QMAKE) "C:/workspace/SymbianZoneApp/SymbianZoneApp.pro"  -spec ..\..\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

bld.inf: C:/workspace/SymbianZoneApp/SymbianZoneApp.pro
	$(QMAKE) "C:/workspace/SymbianZoneApp/SymbianZoneApp.pro"  -spec ..\..\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

c:\workspace\SymbianZoneApp\SymbianZoneApp.loc: 
	$(QMAKE) "C:/workspace/SymbianZoneApp/SymbianZoneApp.pro"  -spec ..\..\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

debug: c:\workspace\SymbianZoneApp\SymbianZoneApp.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
clean-debug: bld.inf
	$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
freeze-debug: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
release: c:\workspace\SymbianZoneApp\SymbianZoneApp.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
clean-release: bld.inf
	$(SBS) reallyclean --toolcheck=off -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
freeze-release: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

debug-winscw: c:\workspace\SymbianZoneApp\SymbianZoneApp.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc
clean-debug-winscw: bld.inf
	$(SBS) reallyclean -c winscw_udeb.mwccinc
freeze-debug-winscw: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc
debug-gcce: c:\workspace\SymbianZoneApp\SymbianZoneApp.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-gcce: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
debug-armv5: c:\workspace\SymbianZoneApp\SymbianZoneApp.loc bld.inf
	$(SBS) -c armv5_udeb
clean-debug-armv5: bld.inf
	$(SBS) reallyclean -c armv5_udeb
freeze-debug-armv5: bld.inf
	$(SBS) freeze -c armv5_udeb
debug-armv6: c:\workspace\SymbianZoneApp\SymbianZoneApp.loc bld.inf
	$(SBS) -c armv6_udeb
clean-debug-armv6: bld.inf
	$(SBS) reallyclean -c armv6_udeb
freeze-debug-armv6: bld.inf
	$(SBS) freeze -c armv6_udeb
release-gcce: c:\workspace\SymbianZoneApp\SymbianZoneApp.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-gcce: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
release-armv5: c:\workspace\SymbianZoneApp\SymbianZoneApp.loc bld.inf
	$(SBS) -c armv5_urel
clean-release-armv5: bld.inf
	$(SBS) reallyclean -c armv5_urel
freeze-release-armv5: bld.inf
	$(SBS) freeze -c armv5_urel
release-armv6: c:\workspace\SymbianZoneApp\SymbianZoneApp.loc bld.inf
	$(SBS) -c armv6_urel
clean-release-armv6: bld.inf
	$(SBS) reallyclean -c armv6_urel
freeze-release-armv6: bld.inf
	$(SBS) freeze -c armv6_urel
debug-armv5-gcce4.4.1: c:\workspace\SymbianZoneApp\SymbianZoneApp.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
release-armv5-gcce4.4.1: c:\workspace\SymbianZoneApp\SymbianZoneApp.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
debug-armv6-gcce4.4.1: c:\workspace\SymbianZoneApp\SymbianZoneApp.loc bld.inf
	$(SBS) -c arm.v6.udeb.gcce4_4_1
clean-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.udeb.gcce4_4_1
freeze-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.udeb.gcce4_4_1
release-armv6-gcce4.4.1: c:\workspace\SymbianZoneApp\SymbianZoneApp.loc bld.inf
	$(SBS) -c arm.v6.urel.gcce4_4_1
clean-release-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.urel.gcce4_4_1
freeze-release-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.urel.gcce4_4_1

export: bld.inf
	$(SBS) export -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

cleanexport: bld.inf
	$(SBS) cleanexport -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

freeze: freeze-release

check: first

run:
	call C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/release/winscw/udeb/SymbianZoneApp.exe $(QT_RUN_OPTIONS)

runonphone: sis
	runonphone $(QT_RUN_ON_PHONE_OPTIONS) --sis SymbianZoneApp.sis SymbianZoneApp.exe $(QT_RUN_OPTIONS)

SymbianZoneApp_template.pkg: C:/workspace/SymbianZoneApp/SymbianZoneApp.pro
	$(MAKE) -f $(MAKEFILE) qmake

SymbianZoneApp_installer.pkg: C:/workspace/SymbianZoneApp/SymbianZoneApp.pro
	$(MAKE) -f $(MAKEFILE) qmake

SymbianZoneApp_stub.pkg: C:/workspace/SymbianZoneApp/SymbianZoneApp.pro
	$(MAKE) -f $(MAKEFILE) qmake

sis: SymbianZoneApp_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_sis:
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) SymbianZoneApp_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_sis: SymbianZoneApp_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_unsigned_sis:
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) -o SymbianZoneApp_template.pkg $(QT_SIS_TARGET)

SymbianZoneApp.sis:
	$(MAKE) -f $(MAKEFILE) sis

installer_sis: SymbianZoneApp_installer.pkg sis
	$(MAKE) -f $(MAKEFILE) ok_installer_sis

ok_installer_sis: SymbianZoneApp_installer.pkg
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) SymbianZoneApp_installer.pkg - $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_installer_sis: SymbianZoneApp_installer.pkg unsigned_sis
	$(MAKE) -f $(MAKEFILE) ok_unsigned_installer_sis

ok_unsigned_installer_sis: SymbianZoneApp_installer.pkg
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) -o SymbianZoneApp_installer.pkg

fail_sis_nocache:
	$(error Project has to be built or QT_SIS_TARGET environment variable has to be set before calling 'SIS' target)

stub_sis: SymbianZoneApp_stub.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_stub_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_stub_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_stub_sis:
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat -s $(QT_SIS_OPTIONS) SymbianZoneApp_stub.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

deploy: sis
	call SymbianZoneApp.sis

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc\moc_qmlapplicationviewer.cpp moc\moc_application.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc\moc_qmlapplicationviewer.cpp moc\moc_application.cpp
moc\moc_qmlapplicationviewer.cpp: qmlapplicationviewer\qmlapplicationviewer.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\workspace\SymbianZoneApp\qmlapplicationviewer\qmlapplicationviewer.h -o c:\workspace\SymbianZoneApp\moc\moc_qmlapplicationviewer.cpp

moc\moc_application.cpp: application.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\workspace\SymbianZoneApp\application.h -o c:\workspace\SymbianZoneApp\moc\moc_application.cpp

compiler_rcc_make_all: rcc\qrc_SymbianZoneApp.cpp
compiler_rcc_clean:
	-$(DEL_FILE) rcc\qrc_SymbianZoneApp.cpp
rcc\qrc_SymbianZoneApp.cpp: SymbianZoneApp.qrc \
		qml\SymbianZoneApp\InstructionPage4.qml \
		qml\SymbianZoneApp\ProgramPage.qml \
		qml\SymbianZoneApp\RestoregamePage.qml \
		qml\SymbianZoneApp\logo.svg \
		qml\SymbianZoneApp\folder.svg \
		qml\SymbianZoneApp\DriveInfoComponent.qml \
		qml\SymbianZoneApp\InstructionPage1.qml \
		qml\SymbianZoneApp\MainPage_backup.qml \
		qml\SymbianZoneApp\InfoPage.qml \
		qml\SymbianZoneApp\OkDialog2.qml \
		qml\SymbianZoneApp\SavegamePage.qml \
		qml\SymbianZoneApp\BackupPage.qml \
		qml\SymbianZoneApp\AboutPage.qml \
		qml\SymbianZoneApp\RestorePage.qml \
		qml\SymbianZoneApp\ProgramPage1.qml \
		qml\SymbianZoneApp\FileDialog.qml \
		qml\SymbianZoneApp\HelpPage.qml \
		qml\SymbianZoneApp\file.svg \
		qml\SymbianZoneApp\InstructionPage2.qml \
		qml\SymbianZoneApp\OkDialog1.qml \
		qml\SymbianZoneApp\MainPage.qml \
		qml\SymbianZoneApp\done.svg \
		qml\SymbianZoneApp\main.qml \
		qml\SymbianZoneApp\LongTextPage.qml \
		qml\SymbianZoneApp\InstructionPage3.qml \
		qml\SymbianZoneApp\HelpPage1.qml \
		qml\SymbianZoneApp\OkDialog.qml \
		qml\SymbianZoneApp\SelectionbackupPage.qml \
		qml\SymbianZoneApp\FilesPage.qml \
		qml\SymbianZoneApp\InstructionPage.qml \
		qml\SymbianZoneApp\GamePage.qml \
		qml\SymbianZoneApp\image\logo.svg \
		qml\SymbianZoneApp\image\about.svg \
		qml\SymbianZoneApp\image\Restore1.svg \
		qml\SymbianZoneApp\image\Restore.svg \
		qml\SymbianZoneApp\image\note_info.svg \
		qml\SymbianZoneApp\image\VK1.png \
		qml\SymbianZoneApp\image\BackUp1.svg \
		qml\SymbianZoneApp\image\RestGame1.svg \
		qml\SymbianZoneApp\image\SaveGames.svg \
		qml\SymbianZoneApp\image\note.svg \
		qml\SymbianZoneApp\image\file.svg \
		qml\SymbianZoneApp\image\SaveGames1.svg \
		qml\SymbianZoneApp\image\close.svg \
		qml\SymbianZoneApp\image\help.svg \
		qml\SymbianZoneApp\image\ok.svg \
		qml\SymbianZoneApp\image\info.png \
		qml\SymbianZoneApp\image\RestGame.svg \
		qml\SymbianZoneApp\image\BackUp.svg \
		qml\SymbianZoneApp\image\Update.svg \
		qml\SymbianZoneApp\image\HelpPage.svg \
		qml\SymbianZoneApp\image\warning.svg
	c:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\rcc.exe -name SymbianZoneApp c:\workspace\SymbianZoneApp\SymbianZoneApp.qrc -o c:\workspace\SymbianZoneApp\rcc\qrc_SymbianZoneApp.cpp

compiler_image_collection_make_all: ui\qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui\qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

dodistclean:
	-@ if EXIST "c:\workspace\SymbianZoneApp\SymbianZoneApp_template.pkg" $(DEL_FILE)  "c:\workspace\SymbianZoneApp\SymbianZoneApp_template.pkg"
	-@ if EXIST "c:\workspace\SymbianZoneApp\SymbianZoneApp_stub.pkg" $(DEL_FILE)  "c:\workspace\SymbianZoneApp\SymbianZoneApp_stub.pkg"
	-@ if EXIST "c:\workspace\SymbianZoneApp\SymbianZoneApp_installer.pkg" $(DEL_FILE)  "c:\workspace\SymbianZoneApp\SymbianZoneApp_installer.pkg"
	-@ if EXIST "c:\workspace\SymbianZoneApp\Makefile" $(DEL_FILE)  "c:\workspace\SymbianZoneApp\Makefile"
	-@ if EXIST "c:\workspace\SymbianZoneApp\SymbianZoneApp_exe.mmp" $(DEL_FILE)  "c:\workspace\SymbianZoneApp\SymbianZoneApp_exe.mmp"
	-@ if EXIST "c:\workspace\SymbianZoneApp\SymbianZoneApp_reg.rss" $(DEL_FILE)  "c:\workspace\SymbianZoneApp\SymbianZoneApp_reg.rss"
	-@ if EXIST "c:\workspace\SymbianZoneApp\SymbianZoneApp.rss" $(DEL_FILE)  "c:\workspace\SymbianZoneApp\SymbianZoneApp.rss"
	-@ if EXIST "c:\workspace\SymbianZoneApp\SymbianZoneApp.loc" $(DEL_FILE)  "c:\workspace\SymbianZoneApp\SymbianZoneApp.loc"
	-@ if EXIST "c:\workspace\SymbianZoneApp\bld.inf" $(DEL_FILE)  "c:\workspace\SymbianZoneApp\bld.inf"

distclean: clean dodistclean

clean: bld.inf
	-$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1


